# Generated by Django 5.2.7 on 2025-10-02 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address_street', models.CharField(blank=True, max_length=255)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_state', models.CharField(blank=True, max_length=50)),
                ('address_zip', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('Furnace', 'Furnace'), ('Air Conditioner', 'Air Conditioner'), ('Humidifier', 'Humidifier'), ('Filter System', 'Filter System'), ('Water Heater', 'Water Heater')], max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('warranty_expiration_date', models.DateField(blank=True, null=True)),
                ('filter_size', models.CharField(blank=True, max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('technician_name', models.CharField(blank=True, max_length=100)),
                ('service_type', models.CharField(choices=[('Maintenance', 'Maintenance'), ('Repair', 'Repair'), ('Installation', 'Installation')], max_length=50)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_history', to='api.equipment')),
            ],
        ),
    ]
