# Generated by Django 5.2.7 on 2025-10-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='ptorequest',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='servicehistory',
            options={'ordering': ['-service_date']},
        ),
        migrations.AlterModelOptions(
            name='timelog',
            options={'ordering': ['-clock_in']},
        ),
        migrations.RemoveField(
            model_name='client',
            name='address_street',
        ),
        migrations.AddField(
            model_name='client',
            name='address_line_1',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='recurrence_rule',
            field=models.TextField(blank=True, default='', help_text='iCal RRULE string'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('AS', 'American Samoa'), ('DC', 'District of Columbia'), ('FM', 'Federated States of Micronesia'), ('GU', 'Guam'), ('MH', 'Marshall Islands'), ('MP', 'Northern Mariana Islands'), ('PW', 'Palau'), ('PR', 'Puerto Rico'), ('VI', 'Virgin Islands')], default='', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_zip',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='client',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text="e.g., {'reminders': 'email'}"),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='filter_size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='check_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenancereminder',
            name='reminder_type',
            field=models.CharField(blank=True, default='', help_text="e.g., 'Annual Summer Tune-Up'", max_length=100),
        ),
        migrations.AlterField(
            model_name='part',
            name='manual_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='part',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ptorequest',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='servicehistory',
            name='technician_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
