# Generated by Django 5.2.7 on 2025-10-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_appointment_options_alter_auditlog_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("furnace", "Furnace"),
                            ("ac", "Air Conditioner"),
                            ("heat_pump", "Heat Pump"),
                            ("coil", "Coil"),
                            ("thermostat", "Thermostat"),
                            ("humidifier", "Humidifier"),
                            ("air_handler", "Air Handler"),
                        ],
                        max_length=50,
                    ),
                ),
                ("manufacturer", models.CharField(max_length=100)),
                ("model_number", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "filter_size",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "refrigerant_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "seer_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "price_msrp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tonnage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("warranty_years", models.PositiveIntegerField(blank=True, null=True)),
                ("common_parts", models.JSONField(blank=True, default=list)),
                ("specs", models.JSONField(blank=True, default=dict)),
                ("manual_url", models.URLField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Equipment (Database)",
                "verbose_name_plural": "Equipment (Database)",
                "ordering": ["manufacturer", "model_number"],
            },
        ),
    ]
