# Generated by Django 5.2.7 on 2025-10-02 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_invoice_check_number_invoice_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="api.client",
            ),
        ),
    ]
