# Generated by Django 5.2.7 on 2025-10-02 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_create_secretary_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="equipment_type",
            field=models.CharField(
                choices=[
                    ("Furnace", "Furnace"),
                    ("Air Conditioner", "Air Conditioner"),
                    ("Humidifier", "Humidifier"),
                    ("Coil", "Coil"),
                    ("Thermostat", "Thermostat"),
                    ("Tank Water Heater", "Tank Water Heater"),
                    ("Tankless Water Heater", "Tankless Water Heater"),
                    ("Water Softener", "Water Softener"),
                    ("Mini Split", "Mini Split"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "reminder_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to send a reminder notification.",
                        null=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="api.client",
                    ),
                ),
                (
                    "technicians",
                    models.ManyToManyField(
                        related_name="appointments", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#FFFFFF",
                        help_text="Hex color code for the user's calendar events",
                        max_length=7,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
