# Generated by Django 5.2.7 on 2025-10-03 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_assign_admin_role_to_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="appointment",
            name="is_partially_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="is_priority",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="travel_time",
            field=models.PositiveIntegerField(
                default=0, help_text="Travel time in minutes"
            ),
        ),
        migrations.AddField(
            model_name="servicehistory",
            name="estimate_pdf_path",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Credit Card", "Credit Card"),
                    ("Check", "Check"),
                    ("Cash", "Cash"),
                    ("Bank Loan", "Bank Loan"),
                    ("N/A", "N/A"),
                ],
                default="N/A",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="attachments/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="api.invoice",
                    ),
                ),
                (
                    "service_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="api.servicehistory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appointment",
            name="job_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.jobtype",
            ),
        ),
    ]
