# Generated by Django 5.2.7 on 2025-10-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_jobtype_appointment_is_partially_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='activity',
            field=models.JSONField(blank=True, default=list, help_text='A log of timeline activities for the client'),
        ),
    ]