# Generated by Django 5.2.7 on 2025-10-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_advanced_business_logic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_partially_complete',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reminder_datetime',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_path',
        ),
        migrations.RemoveField(
            model_name='servicehistory',
            name='estimate_pdf_path',
        ),
        migrations.RemoveField(
            model_name='servicehistory',
            name='service_type',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Overdue', 'Overdue'), ('Pending Payment', 'Pending Payment')], default='Unpaid', max_length=20),
        ),
    ]
